name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: cd into project
      run:  cd project/
    - name: Grant execute permission for gradlew
      run: chmod +x project/gradlew              
    - name: Build and test
      run: ./gradlew deployReports